name: Build Typst SVG

on:
  workflow_dispatch: 
  push:
    paths:
      - '**.typ'
      - '!notes.svg'

permissions:
  contents: write

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile notes.typ
        run: typst compile notes.typ --font-path ./typst_assets --format svg

      - name: Commit and Push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add notes.svg
          git commit -m "Render notes.typ [skip ci]" || echo "No changes to commit"
          
          git push